// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7I2WsodWOtcrArfjfIXE2e8jgGGb0Lfc',
    appId: '1:976271937331:web:75f30e83d7eecd4f9db846',
    messagingSenderId: '976271937331',
    projectId: 'mess-duty-9e967',
    authDomain: 'mess-duty-9e967.firebaseapp.com',
    storageBucket: 'mess-duty-9e967.firebasestorage.app',
    measurementId: 'G-45N9C84JXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwLh2KcbGpzb1cx4c99XaOyCLiCLlqGvg',
    appId: '1:976271937331:android:dc7725e132a8a0879db846',
    messagingSenderId: '976271937331',
    projectId: 'mess-duty-9e967',
    storageBucket: 'mess-duty-9e967.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPZcl4qbX4EhvFdCxypF1OyzGSZtoPZV8',
    appId: '1:976271937331:ios:fc86953bde89b4149db846',
    messagingSenderId: '976271937331',
    projectId: 'mess-duty-9e967',
    storageBucket: 'mess-duty-9e967.firebasestorage.app',
    iosBundleId: 'com.example.messDuty',
  );
}
